# Generated by Django 3.1.2 on 2020-11-03 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('section_name', models.CharField(max_length=100)),
                ('class_name', models.CharField(max_length=100)),
                ('school_name', models.CharField(max_length=100)),
                ('mobile', models.IntegerField()),
                ('marathi_marks', models.IntegerField()),
                ('english_marks', models.IntegerField()),
                ('hindi_marks', models.IntegerField()),
                ('maths_marks', models.IntegerField()),
                ('science_marks', models.IntegerField()),
                ('social_marks', models.IntegerField()),
            ],
        ),
    ]
